import { z } from 'zod';
const textOrNull=z.string().nullable();
// This is the Rust-shaped boundary. Optional coverage/count metadata is additive;
// older valid list envelopes remain readable with safe UI fallbacks.
const sourceUrl=z.string().url().refine(value=>{try{return ['http:','https:'].includes(new URL(value).protocol);}catch{return false;}},'source URL must use HTTP or HTTPS');
const locationShape={facility_id:z.string().uuid(),canonical_name:z.string().nullable(),city:textOrNull,country_code:z.string().regex(/^[A-Z]{2}$/),category:z.string(),source_type:z.enum(['official','secondary','user_submitted']),publication_profile:z.enum(['official','secondary','community']),factual_review_status:z.string(),privacy_screening_status:z.literal('passed'),project_approval:z.string(),reviewer_role:textOrNull,publication_warning:textOrNull,display_precision:z.enum(['exact','city','unmapped']),latitude:z.number().finite().nullable(),longitude:z.number().finite().nullable(),first_observed_at:textOrNull,last_observed_at:textOrNull,observation_count:z.number().int().nonnegative().nullable(),lifecycle_status:z.enum(['active_observed','explicitly_closed','not_seen_recently','status_unknown']),provenance_source_id:z.string(),provenance_source:z.string().nullable(),provenance_source_name:z.string(),provenance_source_url:sourceUrl,provenance_retrieved_at:z.string(),source_rights_status:z.string(),release_id:z.string(),release_ruleset_version:z.string()};
const coordinateRules=(row:{latitude:number|null;longitude:number|null;display_precision:string},ctx:z.RefinementCtx)=>{if((row.latitude===null)!==(row.longitude===null))ctx.addIssue({code:z.ZodIssueCode.custom,message:'coordinate pair must be complete'});if(row.display_precision==='unmapped'&&(row.latitude!==null||row.longitude!==null))ctx.addIssue({code:z.ZodIssueCode.custom,message:'unmapped record cannot have coordinates'});if(row.display_precision!=='unmapped'&&(row.latitude===null||row.longitude===null))ctx.addIssue({code:z.ZodIssueCode.custom,message:'mapped record requires coordinates'});};
export const locationSchema=z.object(locationShape).superRefine(coordinateRules);
export const testReleaseLocationSchema=z.object({...locationShape,canonical_name:z.string().nullable(),publication_profile:z.enum(['official','secondary','community']).nullable(),privacy_screening_status:z.enum(['pending','passed','failed']),project_approval:z.union([z.enum(['pending','approved']),z.literal(false),z.literal('not-approved')]),provenance_source:z.string().nullable().optional().default(null),source_rights_status:z.string().optional().default('unknown'),release_ruleset_version:z.string().nullable()}).superRefine(coordinateRules);
export const envelopeSchema=z.object({data:z.array(locationSchema),api_version:z.literal('v2'),meta:z.object({release_id:z.string().nullable(),ruleset_version:z.string().optional(),release_created_at:z.string().optional(),profile:z.enum(['official','secondary','community']),next_cursor:z.string().nullable().optional(),coverage_note:z.string().min(1),coverage_scope:z.string().optional(),count_semantics:z.string().optional(),query:z.object({q:z.string().nullable().optional(),filters:z.record(z.string(),z.string().nullable())}).optional()})});
export type WireEnvelope=z.infer<typeof envelopeSchema>;export type WireLocation=z.infer<typeof locationSchema>;
export type WireTestReleaseLocation=z.infer<typeof testReleaseLocationSchema>;
export const detailEnvelopeSchema=z.object({data:locationSchema,api_version:z.literal('v2'),meta:z.object({release_id:z.string(),ruleset_version:z.string(),release_created_at:z.string(),profile:z.enum(['official','secondary','community'])})});
export type DetailEnvelope=z.infer<typeof detailEnvelopeSchema>;

