import type { Map as LeafletMap, Marker } from 'leaflet';
import type { MapAdapter } from './MapAdapter';
import type { MapDisplayItem } from './mapProjection';
type MarkerFactory = (item: MapDisplayItem, map: LeafletMap) => Marker;
export class LeafletMapAdapter implements MapAdapter {
  #map: LeafletMap | null = null; #markers = new Map<string, Marker>(); #disposed = false; #makeMarker: MarkerFactory | null = null;
  async mount(container: HTMLElement, onSelect?: (id:string) => void): Promise<void> { const leaflet = await import('leaflet'); if (this.#disposed) return; this.#makeMarker = (item, map) => { const cluster = 'count' in item; const city = !cluster && item.precision === 'city'; const marker = leaflet.marker([item.lat, item.lon], { title: item.label, keyboard: true, icon: cluster ? leaflet.divIcon({ className: 'uec-cluster', html: `<span aria-hidden="true">${item.count}</span>` }) : city ? leaflet.divIcon({ className: 'uec-city-point', html: '<span aria-hidden="true"></span>' }) : undefined }).addTo(map); if (cluster) marker.on('click', () => map.setView([item.lat, item.lon], Math.min(map.getZoom() + 2, 18))); else if (onSelect) marker.on('click', () => onSelect(item.id)); return marker; }; this.#map = leaflet.map(container, { attributionControl: false, zoomControl: true }).setView([55, 10], 6); this.#map.getContainer().style.background = '#ded8cc'; }
  update(items: readonly MapDisplayItem[], selectedId: string | null): void { if (!this.#map || !this.#makeMarker) return; const active = new Set(items.map((item) => item.id)); for (const [id, marker] of this.#markers) { if (!active.has(id)) { marker.remove(); this.#markers.delete(id); } } for (const item of items) { const marker = this.#markers.get(item.id) ?? this.#makeMarker(item, this.#map); this.#markers.set(item.id, marker); const selected = 'count' in item ? item.memberIds.includes(selectedId ?? '') : selectedId === null || selectedId === item.id; marker.setOpacity(selected ? 1 : 0.55); } }
  destroy(): void { this.#disposed = true; for (const marker of this.#markers.values()) marker.remove(); this.#markers.clear(); this.#map?.remove(); this.#map = null; this.#makeMarker = null; }
}
