<script lang="ts">
  import type { Direction, DirectionViewProps, Precision, Scenario } from '../../contract';
  import { DIRECTIONS, SCENARIOS } from '../../contract';
  import MapSurface from '../../components/MapSurface.svelte';
  import RecordList from '../../components/RecordList.svelte';

  let { state, records, dispatch }: DirectionViewProps = $props();
  const categories = ['Poultry', 'Pig', 'Dairy', 'Processing', 'Laboratory', 'Aquaculture'];
  const precisions: readonly Precision[] = ['exact', 'city', 'coarse', 'unmapped'];
  const selectedRecord = $derived(records.find(record => record.id === state.selectedId) ?? null);
  const mappedRecords = $derived(records.filter(record => record.latitude !== null && record.longitude !== null));
  const activeFilterCount = $derived(state.filters.categories.length + state.filters.precisions.length);

  function toggleCategory(category: string, checked: boolean) {
    const categories = checked ? [...state.filters.categories, category] : state.filters.categories.filter(item => item !== category);
    dispatch({ type: 'filters', value: { ...state.filters, categories } });
  }
  function togglePrecision(precision: Precision, checked: boolean) {
    const values = checked ? [...state.filters.precisions, precision] : state.filters.precisions.filter(item => item !== precision);
    dispatch({ type: 'filters', value: { ...state.filters, precisions: values } });
  }
</script>

<section class="field-view" data-scenario={state.scenario} aria-label="Field map design direction">
  <header class="spine">
    <a class="brand" href="#/map?f1a=field" aria-label="Until Every Cage map home"><span class="brand-mark" aria-hidden="true">UEC</span><span>Until Every Cage</span></a>
    <nav aria-label="Main navigation"><a href="#/map?f1a=field" aria-current="page">Map</a><a href="#/database">Database</a></nav>
    <form class="search" role="search" onsubmit={event => event.preventDefault()}>
      <label for="field-search">Search all synthetic records</label><span aria-hidden="true">⌕</span>
      <input id="field-search" type="search" placeholder="Name, category, country, or place" value={state.query} oninput={event => dispatch({ type: 'query', value: event.currentTarget.value })} /><kbd aria-hidden="true">/</kbd>
    </form>
    <details class="filters">
      <summary><span aria-hidden="true">≡</span> Filters {#if activeFilterCount}<b>{activeFilterCount}</b>{/if}</summary>
      <div class="filter-sheet">
        <header><strong>Refine records</strong><small>{activeFilterCount} active</small></header>
        <p class="filter-help">OR within each group · groups narrow together</p>
        <fieldset><legend>Category</legend>{#each categories as category}<label><input type="checkbox" checked={state.filters.categories.includes(category)} onchange={event => toggleCategory(category, event.currentTarget.checked)} />{category}</label>{/each}</fieldset>
        <fieldset><legend>Location precision</legend>{#each precisions as precision}<label><input type="checkbox" checked={state.filters.precisions.includes(precision)} onchange={event => togglePrecision(precision, event.currentTarget.checked)} />{precision === 'exact' ? 'Exact site' : precision === 'city' ? 'City-level' : precision === 'coarse' ? 'Coarse area' : 'Unmapped'}</label>{/each}</fieldset>
        <button type="button" onclick={() => dispatch({ type: 'reset-filters' })}>Reset search and filters</button>
      </div>
    </details>
    <div class="review-tools" aria-label="Development review controls">
      <label>Direction<select aria-label="Direction" value={state.direction} onchange={event => dispatch({ type: 'direction', value: event.currentTarget.value as Direction })}>{#each DIRECTIONS as direction}<option value={direction}>{direction}</option>{/each}</select></label>
      <label>Scenario<select aria-label="Scenario" value={state.scenario} onchange={event => dispatch({ type: 'scenario', value: event.currentTarget.value as Scenario })}>{#each SCENARIOS as scenario}<option value={scenario}>{scenario}</option>{/each}</select></label>
    </div>
    <span class="data-mark"><i aria-hidden="true"></i>Synthetic · development only</span>
  </header>

  <section class:results-closed={!state.listOpen} class="map-stage" aria-label="Investigative map field">
    <h1 class="sr-only">Investigative map</h1>
    {#if state.scenario === 'loading'}
      <div class="status" role="status"><i></i><strong>Loading synthetic records</strong><span>Building the field view…</span></div>
    {:else if state.scenario === 'error'}
      <div class="status error" role="alert"><i></i><strong>Records unavailable</strong><span>The test failure is contained. No live fallback was attempted.</span></div>
    {:else}
      <MapSurface records={mappedRecords} {state} onselect={id => dispatch({ type: 'select', value: id })} oncluster={value => dispatch({ type: 'cluster', value })} onbasemap={value => dispatch({ type: 'basemap', value })} onviewport={value => dispatch({ type: 'viewport', value })} />
    {/if}
    {#if state.scenario === 'empty' || (state.scenario !== 'loading' && state.scenario !== 'error' && records.length === 0)}
      <div class="empty" role="status"><small>NO ELIGIBLE RECORDS</small><p>No synthetic records match these search and filter settings.</p><button type="button" onclick={() => dispatch({ type: 'reset-filters' })}>Clear search and filters</button></div>
    {/if}
    {#if selectedRecord && state.scenario !== 'loading' && state.scenario !== 'error'}
      <aside class="reading-sheet" aria-labelledby="record-title" aria-live="polite">
        <div class="sheet-grip" aria-hidden="true"></div>
        <div class="sheet-meta"><span>Selected record</span><span>{selectedRecord.id}</span></div>
        <button class="close" type="button" aria-label="Close record preview" onclick={() => dispatch({ type: 'select', value: null })}>×</button>
        <p class="category">{selectedRecord.category}<i> / </i>{selectedRecord.precision} location</p>
        <h2 id="record-title">{selectedRecord.name}</h2>
        <p class="place"><span aria-hidden="true">⌖</span> {selectedRecord.locality}, {selectedRecord.country}</p>
        <div class="rule"></div><p class="note">Synthetic record for interface review. It makes no factual claim.</p>
      </aside>
    {/if}
  </section>

  <section class:closed={!state.listOpen} class="results" aria-label="Synchronized results">
    <div class="results-bar">
      <button class="results-toggle" type="button" aria-expanded={state.listOpen} aria-controls="field-record-list" onclick={() => dispatch({ type: 'list', value: !state.listOpen })}>
        <span aria-hidden="true">{state.listOpen ? '⌄' : '⌃'}</span>{state.listOpen ? 'Results' : 'Browse results'}<b>{records.length}</b>
      </button>
      <p><i aria-hidden="true"></i>{mappedRecords.length} mapped <span>·</span> {records.filter(record => record.precision === 'unmapped').length} without coordinates</p>
      <small>Select a mark or record to inspect</small>
      <em><i aria-hidden="true"></i>List ↔ map</em>
    </div>
    <div id="field-record-list" class="results-content" hidden={!state.listOpen || state.scenario === 'loading' || state.scenario === 'error'}>
      <RecordList records={records} selectedId={state.selectedId} onselect={id => dispatch({ type: 'select', value: id })} />
    </div>
  </section>
</section>

<style>
  .field-view{--ink:#ecebe5;--muted:#9a9f99;--line:#353c3a;--accent:#d3a96a;position:fixed;inset:0;overflow:hidden;color:var(--ink);background:#111515;font-family:"Arial Narrow","Aptos Narrow","Roboto Condensed","Segoe UI",sans-serif;letter-spacing:.015em}
  .field-view :global(*){box-sizing:border-box}.field-view :global(a){color:inherit}.field-view :global(button),.field-view :global(input),.field-view :global(select){font:inherit}.field-view :global(button:focus-visible),.field-view :global(a:focus-visible),.field-view :global(input:focus-visible),.field-view :global(select:focus-visible),.field-view summary:focus-visible{outline:2px solid #f2d29a;outline-offset:3px}
  .spine{position:absolute;z-index:10;inset:0 0 auto;height:5.25rem;display:grid;grid-template-columns:auto auto minmax(12rem,1fr) auto auto auto;align-items:center;gap:clamp(.45rem,1vw,1rem);padding:.55rem clamp(.75rem,2vw,1.6rem);border-bottom:1px solid #424947;background:#151a19f2;box-shadow:0 1rem 2.5rem #05080730}
  .brand{display:flex;align-items:center;gap:.6rem;text-decoration:none;white-space:nowrap;font:600 .86rem Georgia,serif}.brand-mark{display:grid;place-items:center;width:2rem;height:2rem;border:1px solid #8e8d7f;color:#e7d6b6;font:700 .57rem ui-monospace,monospace;letter-spacing:.06em}
  nav{display:flex;align-items:center;gap:.15rem;height:2.5rem;padding-left:.3rem;border-left:1px solid var(--line)}nav a{position:relative;padding:.6rem .7rem;color:#aeb2ac!important;font:700 .61rem ui-monospace,monospace;letter-spacing:.12em;text-decoration:none;text-transform:uppercase}nav a[aria-current=page]{color:var(--ink)!important}nav a[aria-current=page]::after{position:absolute;right:.7rem;bottom:-.82rem;left:.7rem;height:2px;background:var(--accent);content:""}
  .search{position:relative;display:flex;align-items:center;min-width:0;height:2.65rem;border:1px solid #4d5651;background:#101414}.search label{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap}.search>span{padding:0 .7rem;color:var(--accent);font:1.3rem Georgia,serif}.search input{min-width:0;width:100%;height:100%;padding:.2rem .25rem;border:0;color:var(--ink);background:transparent;font:.82rem Georgia,serif}.search input::placeholder{color:#747d78;opacity:1}.search input:focus{outline:none}.search kbd{flex:0 0 auto;margin:0 .55rem;padding:.2rem .3rem;border:1px solid #3d4441;color:#8c948f;font:.56rem ui-monospace,monospace}
  .filters{position:relative}.filters summary{display:flex;align-items:center;gap:.5rem;min-height:2.5rem;padding:0 .75rem;border:1px solid #4d5651;color:#d6d8d1;cursor:pointer;font:700 .62rem ui-monospace,monospace;letter-spacing:.08em;list-style:none;text-transform:uppercase;white-space:nowrap}.filters summary::-webkit-details-marker{display:none}.filters summary:hover{background:#222a27}.filters summary>span{color:var(--accent);font:1rem Georgia,serif}.filters summary b{display:grid;place-items:center;min-width:1.2rem;height:1.2rem;border-radius:50%;color:#161a18;background:var(--accent);font-size:.62rem}
  .filter-sheet{position:absolute;top:calc(100% + .65rem);right:0;z-index:12;width:min(20rem,calc(100vw - 1.5rem));padding:1rem;border:1px solid #555f59;background:#171d1b;box-shadow:0 1rem 3rem #050807bb}.filter-sheet header{display:flex;justify-content:space-between;padding-bottom:.7rem;border-bottom:1px solid var(--line)}.filter-sheet header strong{font:600 1rem Georgia,serif}.filter-sheet header small{color:var(--muted);font:.63rem ui-monospace,monospace}.filter-sheet fieldset{display:grid;grid-template-columns:1fr 1fr;gap:.5rem .7rem;margin:.9rem 0 0;padding:0;border:0}.filter-sheet legend{grid-column:1/-1;margin-bottom:.2rem;color:#9fa7a1;font:.58rem ui-monospace,monospace;letter-spacing:.11em;text-transform:uppercase}.filter-sheet label{display:flex;align-items:center;gap:.45rem;min-height:1.8rem;color:#d3d5ce;font-size:.75rem}.filter-sheet input{width:.9rem;height:.9rem;margin:0;accent-color:var(--accent)}.filter-sheet button{width:100%;margin-top:1rem;padding:.6rem;border:1px solid #48504b;color:#d6d8d1;background:#202724;cursor:pointer;font:.63rem ui-monospace,monospace}
  .filter-help{margin:.65rem 0 0;color:#aeb7ae;font:.61rem ui-monospace,monospace}
  .review-tools{display:flex;align-items:center;gap:.55rem}.review-tools label{display:flex;align-items:center;gap:.35rem;color:#818984;font:.55rem ui-monospace,monospace;letter-spacing:.06em;text-transform:uppercase}.review-tools select{max-width:5rem;height:2rem;padding:0 .35rem;border:1px solid #414945;border-radius:0;color:#c4c9c2;background:#1a201e;font-size:.63rem;text-transform:capitalize}.data-mark{display:flex;align-items:center;gap:.4rem;color:#b7bdb4;font:.56rem ui-monospace,monospace;letter-spacing:.05em;white-space:nowrap}.data-mark i{width:.38rem;height:.38rem;border-radius:50%;background:var(--accent);box-shadow:0 0 .6rem #d3a96a80}
  .map-stage{position:absolute;inset:5.25rem 0 0;overflow:hidden;background:#202725}.map-stage :global(.map-surface){position:absolute;inset:0;min-height:0;border:0;background-color:#202725;background-image:linear-gradient(#444d4833 1px,transparent 1px),linear-gradient(90deg,#444d4833 1px,transparent 1px),radial-gradient(ellipse at 50% 50%,#323d38 0%,#232b28 54%,#1c2220 100%);background-size:7.2% 12%,7.2% 12%,cover}.map-stage :global(.cartography){inset:12% 5% 10%;color:#77827c;font-size:.58rem;letter-spacing:.18em}.map-stage :global(.marker){box-shadow:0 0 .9rem #070b0a90}.map-stage :global(.marker.exact){width:1.1rem;height:1.1rem;border:1px solid #fff7e7;border-radius:50%;background:#ce6c51}.map-stage :global(.marker.city){width:1.65rem;height:1.65rem;border:3px double #edc47e;border-radius:50%;background:#352e2470;color:#edc47e}.map-stage :global(.marker.coarse){width:3.25rem;height:3.25rem;border:1px dashed #b6d2c5;border-radius:50%;background:#78948724;color:#d9e3d9}.map-stage :global(.marker.active){outline:2px solid #f5ecd9;outline-offset:4px}.map-stage :global(.marker.cluster){width:2.2rem;height:2.2rem;border:1px solid #e5d6ba;border-radius:50%;color:#1c211e;background:#e5d6ba}
  .map-stage :global(.viewport-control){top:1.2rem;left:1.2rem;grid-template-columns:repeat(3,2.35rem);gap:.2rem}.map-stage :global(.viewport-control button),.map-stage :global(.basemap-control button){min-height:2.3rem;border-color:#69716b;color:#dfe3dc;background:#171d1be8;box-shadow:0 .2rem .7rem #080c0b60}.map-stage :global(.viewport-control button:hover),.map-stage :global(.basemap-control button:hover){background:#303a35}.map-stage :global(.basemap-control){top:1.2rem;right:1.2rem}.map-stage :global(.basemap-control button){font:.63rem ui-monospace,monospace;letter-spacing:.08em;text-transform:uppercase}.map-stage :global(.basemap-control button[aria-pressed=true]){border-color:var(--accent);color:#151918;background:#d3a96a}.map-stage :global(.satellite-note){top:4rem;right:1.2rem;color:#e5e4dc;background:#171d1bf2;border:1px solid #5f6861}.map-stage :global(.precision-legend){bottom:1.2rem;left:1.2rem;gap:.42rem;padding:.75rem .85rem;border:1px solid #525b55;color:#d7dbd2;background:#151a19e8;font-size:.6rem;letter-spacing:.05em}.map-stage :global(.glyph){flex:0 0 auto}.map-stage :global(.glyph.exact){border-radius:50%;background:#ce6c51}.map-stage :global(.glyph.city){border-color:#edc47e}.map-stage :global(.glyph.coarse){border-color:#b6d2c5}.map-stage :global(.attribution){right:1rem;bottom:.7rem;color:#b8c0b8;font:.55rem ui-monospace,monospace}.map-stage :global(.cluster-summary){top:5.5rem;left:1.2rem;border-color:#69736b;color:#e6e7df;background:#151a19f5}
  .status,.empty{position:absolute;z-index:4;top:50%;left:50%;width:min(26rem,calc(100% - 2rem));padding:1.3rem 1.4rem;border:1px solid #606961;background:#151a19f5;box-shadow:0 1rem 3rem #090d0c99;transform:translate(-50%,-50%)}.status{display:grid;gap:.45rem;min-width:min(19rem,calc(100% - 2rem))}.status>i{width:2rem;height:2px;margin-bottom:.2rem;background:var(--accent)}.status strong{font:600 1rem Georgia,serif}.status span{color:var(--muted);font-size:.75rem}.status.error>i{background:#d07967}.empty small{color:var(--accent);font:.59rem ui-monospace,monospace;letter-spacing:.14em}.empty p{margin:.6rem 0 1rem;color:#d1d5cf;font:1rem/1.45 Georgia,serif}.empty button{min-height:2.3rem;padding:.4rem .7rem;border:1px solid #747b73;color:var(--ink);background:#222a27;cursor:pointer;font-size:.72rem}
  .reading-sheet{position:absolute;z-index:7;right:clamp(1rem,3.5vw,3.6rem);bottom:18rem;width:min(25rem,calc(100% - 2rem));padding:1.25rem 1.4rem 1.1rem;border:1px solid #68736b;background:#171d1bf2;box-shadow:0 1rem 3rem #080c0b99;animation:arrive .22s ease-out both}.map-stage.results-closed .reading-sheet{bottom:4rem}.sheet-grip{display:none}.sheet-meta{display:flex;justify-content:space-between;padding-bottom:.8rem;border-bottom:1px solid #3b443f;color:#929b93;font:.57rem ui-monospace,monospace;letter-spacing:.1em;text-transform:uppercase}.sheet-meta span:last-child{color:#b8c0b7;font-variant-numeric:tabular-nums}.close{position:absolute;top:.55rem;right:.55rem;display:grid;place-items:center;width:2rem;height:2rem;border:1px solid #525b55;color:#daddd5;background:#1d2421;cursor:pointer;font-size:1.15rem}.category{margin:1rem 2.4rem .35rem 0;color:var(--accent);font:.6rem ui-monospace,monospace;letter-spacing:.09em;text-transform:uppercase}.category i{color:#778179;font-style:normal}.reading-sheet h2{margin:0;padding-right:1rem;font:500 clamp(1.15rem,2vw,1.5rem)/1.2 Georgia,serif;letter-spacing:-.02em}.place{margin:.7rem 0;color:#c1c8bf;font-size:.78rem}.place span{color:var(--accent)}.rule{height:1px;margin-top:1rem;background:#39413d}.note{margin:.8rem 0 0;color:#929a93;font:.67rem/1.4 Georgia,serif}
  .results{position:absolute;z-index:8;right:0;bottom:0;left:0;border-top:1px solid #57615a;background:#151a19f7;box-shadow:0 -.8rem 2.2rem #060a0950}.results-bar{display:flex;align-items:center;gap:1.1rem;min-height:3.2rem;padding:.35rem clamp(.75rem,1.6vw,1.4rem)}.results-toggle{display:flex;align-items:center;gap:.55rem;min-height:2.3rem;padding:0 .2rem;border:0;color:#eeeae1;background:transparent;cursor:pointer;font:700 .64rem ui-monospace,monospace;letter-spacing:.1em;text-transform:uppercase;white-space:nowrap}.results-toggle>span{color:var(--accent);font-size:1.1rem}.results-toggle b{display:grid;place-items:center;min-width:1.45rem;height:1.45rem;border:1px solid #4c554f;border-radius:50%;color:#d6d9d1;font:.61rem ui-monospace,monospace;font-variant-numeric:tabular-nums}.results-bar p{display:flex;align-items:center;gap:.45rem;margin:0;color:#afb6ae;font:.62rem ui-monospace,monospace;font-variant-numeric:tabular-nums}.results-bar p>i{width:.38rem;height:.38rem;border-radius:50%;background:#93a99a}.results-bar>small{margin-left:auto;color:#78817a;font:.62rem Georgia,serif}.results-bar em{display:flex;align-items:center;gap:.35rem;color:#a4aba4;font:normal .58rem ui-monospace,monospace}.results-bar em i{width:2.3rem;height:1px;background:#5b645d}.results-content{max-height:14rem;overflow:auto;border-top:1px solid #333b37}.results-content[hidden]{display:none}.results-content :global(.record-list){overflow:visible;border:0;background:transparent}.results-content :global(.record-list h2){position:absolute;width:1px;height:1px;padding:0;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}.results-content :global(.record-list ol){display:flex;gap:0;margin:0;padding:0;list-style:none}.results-content :global(.record-list li){flex:0 0 min(17rem,26vw);min-width:12rem;border-right:1px solid #333b37;border-bottom:0}.results-content :global(.record-list button){display:flex;flex-direction:column;justify-content:center;min-height:5.4rem;padding:.8rem 1rem;color:#e0e2db;text-align:left}.results-content :global(.record-list button:hover),.results-content :global(.record-list button.active){background:#28312c}.results-content :global(.record-list strong){font:600 .83rem/1.25 Georgia,serif}.results-content :global(.record-list small){margin-top:.4rem;color:#9da69e;font:.59rem ui-monospace,monospace;font-variant-numeric:tabular-nums}
  .sr-only{position:absolute!important;width:1px!important;height:1px!important;padding:0!important;margin:-1px!important;overflow:hidden!important;clip:rect(0,0,0,0)!important;white-space:nowrap!important;border:0!important}@keyframes arrive{from{opacity:0;transform:translateY(.5rem)}to{opacity:1;transform:translateY(0)}}
  .review-tools{display:flex;align-items:center;gap:.55rem}.review-tools label{display:flex;align-items:center;gap:.35rem;color:#818984;font:.55rem ui-monospace,monospace;letter-spacing:.06em;text-transform:uppercase}.review-tools select{max-width:5rem;height:2rem;padding:0 .35rem;border:1px solid #414945;border-radius:0;color:#c4c9c2;background:#1a201e;font-size:.63rem;text-transform:capitalize}
  @media(max-width:68rem){.spine{grid-template-columns:auto auto minmax(12rem,1fr) auto auto auto;gap:.7rem}.data-mark{font-size:.5rem}}
  @media(max-width:48rem){.spine{grid-template-columns:auto 1fr auto;gap:.5rem .7rem;height:auto;min-height:auto;padding:.55rem .75rem .65rem}.brand{grid-column:1;grid-row:1;font-size:.79rem}.spine nav{grid-column:2;grid-row:1;justify-content:flex-end;border:0}.spine nav a{padding-inline:.5rem;font-size:.57rem}.spine nav a[aria-current=page]::after{right:.5rem;bottom:-.66rem;left:.5rem}.data-mark{grid-column:3;grid-row:1;font-size:0}.data-mark i{width:.5rem;height:.5rem}.search{grid-column:1/3;grid-row:2;height:2.45rem}.search kbd{display:none}.filters{grid-column:3;grid-row:2}.filters summary{justify-content:center;min-width:3rem;min-height:2.45rem;padding:0 .5rem}.filters summary{font-size:0}.filters summary>span{font-size:1rem}.filters summary b{font-size:.62rem}.review-tools{grid-column:1/-1;grid-row:3;justify-content:flex-end}.review-tools label{font-size:.52rem}.review-tools select{height:1.8rem}.map-stage{inset:8.65rem 0 0}.map-stage :global(.cartography){inset:17% 7% 24%;flex-direction:column;justify-content:space-between}.map-stage :global(.viewport-control){top:.65rem;left:.65rem;grid-template-columns:repeat(3,2rem);gap:.1rem}.map-stage :global(.viewport-control button){min-height:2rem;padding:.2rem}.map-stage :global(.basemap-control){top:.65rem;right:.65rem}.map-stage :global(.basemap-control button){min-height:2rem;padding:.35rem .5rem;font-size:.55rem}.map-stage :global(.precision-legend){bottom:.55rem;left:.55rem;grid-template-columns:1fr 1fr;gap:.35rem .55rem;padding:.5rem;font-size:.52rem}.map-stage :global(.attribution){right:.55rem;bottom:.4rem;max-width:8rem;text-align:right;font-size:.48rem}.results{max-height:min(44vh,23rem)}.results.closed{max-height:3.2rem}.results-bar{flex-wrap:wrap;gap:.2rem .8rem;min-height:3.1rem;padding:.25rem .75rem}.results-toggle{min-height:2.35rem}.results-bar p{font-size:.54rem}.results-bar>small,.results-bar em{display:none}.results-content{max-height:calc(min(44vh,23rem) - 3.2rem)}.results-content :global(.record-list ol){display:block}.results-content :global(.record-list li){min-width:0;border-right:0;border-bottom:1px solid #333b37}.results-content :global(.record-list button){min-height:4.6rem;padding:.7rem .9rem}.reading-sheet{right:.65rem;bottom:calc(min(44vh,23rem) + .65rem);width:min(24rem,calc(100% - 1.3rem));padding:1rem 1.1rem}.map-stage.results-closed .reading-sheet{bottom:3.8rem}}
  @media(max-width:22rem){.spine{gap:.45rem}.brand>span:last-child{max-width:7.3rem;overflow:hidden;text-overflow:ellipsis}.spine nav{gap:0}.spine nav a{padding-inline:.35rem}.search input{font-size:.73rem}.review-tools{justify-content:space-between}.map-stage{inset-block-start:8.65rem}.results-bar p{max-width:calc(100% - 7rem)}}
  @media(prefers-reduced-motion:reduce){.field-view *,.field-view *::before,.field-view *::after{scroll-behavior:auto!important;animation:none!important;transition:none!important}}
</style>
